#!/usr/bin/env bash
#
# Use http request to send notification to Telegram chat through local Telegram bot

set -eo pipefail
IFS=$'\n\t'

message_text="Backed up ${ARCHIVE_FILE_NAME} with file size: ${ARCHIVE_FILE_SIZE} \
to ${FULL_S3_DIR_PATH}"

if [[ -n "${PRIVATE_NOTIFICATION_URL}" ]]; then
    curl -XPOST \
      --url "${PRIVATE_NOTIFICATION_URL}" \
      --header 'Content-Type: application/json' \
      --data "{\"key\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"${message_text}\"}" \
      --max-time 10 \
      --retry 5
fi
